In [2]:
import pandas as pd
import numpy as np
import glob, os, librosa, soundfile, json, h5py, logging

import librosa.display
from multiprocessing import Pool

from utils.util_process import *

In [6]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/train_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
356230
b'Yb0RFKhbpFJA_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/train_data.h5'
0
[ 52 239 441]


In [5]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/eval_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
61426
b'Ys9d-2nhuJCQ_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/eval_data.h5'
0
[ 74 114 254]


In [7]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/urbansound8k_logmel/train_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
1412
b'100652-3-0-0_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/urbansound8k_logmel/train_data.h5'
0
[20]


In [8]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/urbansound8k_logmel/eval_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
153
b'100795-3-0-0_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/urbansound8k_logmel/eval_data.h5'
0
[20]


In [4]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/hdf5s/train_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
357642
b'Yb0RFKhbpFJA_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/train_data.h5'
0
[ 52 239 441]


In [9]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/hdf5s/eval_index.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print(len(h5_file['audio_name']))
    print(h5_file['audio_name'][0])
    print(h5_file['hdf5_path'][0])
    print(h5_file['index_in_hdf5'][0])
    print(h5_file['target'][0])

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'target']
61579
b'Ys9d-2nhuJCQ_0.wav'
b'/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset_strong/audioset_logmel/eval_data.h5'
0
[ 74 114 254]
