In [1]:
import pandas as pd
import numpy as np
import glob, os, librosa, soundfile, json, h5py, logging

import librosa.display
from multiprocessing import Pool

from utils.util_process import *

import matplotlib.pyplot as plt
from IPython.display import Audio

In [2]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset/unbalanced_train/unbalanced_train_segments_part11.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print('audio_name', h5_file['audio_name'].shape)
    print(h5_file["audio_name"][-1])
    print('logmel', h5_file['logmel'].shape)
    print(h5_file["logmel"][-1])
    print('target', h5_file['target'].shape)
    print(h5_file["target"][-1])

H5文件中的数据集名称: ['audio_name', 'logmel', 'target']
audio_name (46837,)
b'YAWntdC5KcdA.wav'
logmel (46837, 1001, 64)
[[-28.403522 -30.479559 -21.148327 ... -63.115448 -63.44309  -63.52129 ]
 [-24.446318 -26.036314 -19.02189  ... -72.76269  -73.06456  -73.01052 ]
 [-11.871986 -12.951929 -11.565761 ... -80.24462  -81.42192  -81.91469 ]
 ...
 [ -9.241354  -9.1031   -10.928768 ... -65.77278  -69.247154 -70.62378 ]
 [-13.137552 -13.64614  -17.817688 ... -73.52692  -74.10947  -75.63054 ]
 [ -9.878008 -13.950685 -23.213717 ... -72.166214 -74.69422  -74.38403 ]]
target (46837,)
[5 2 0]


In [2]:
# output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset/indexes/unbalanced_train_mini.h5'
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset/indexes/unbalanced_train.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print('audio_name', h5_file["audio_name"].shape)
    print(h5_file["audio_name"][:5])
    print('hdf5_path', h5_file["hdf5_path"].shape)
    print(h5_file["hdf5_path"][:5])
    print('index_in_hdf5', h5_file["index_in_hdf5"].shape)
    print(h5_file["index_in_hdf5"][:5])
    print('target', h5_file["target"].shape)
    print(h5_file["target"][:10])
    print('kfold', h5_file["kfold"].shape)
    print(h5_file["kfold"][:5])
    
    for i in range(10):
        print(i, ':', sum(h5_file["kfold"][:] == i))

H5文件中的数据集名称: ['audio_name', 'hdf5_path', 'index_in_hdf5', 'kfold', 'target']
audio_name (1912134,)
[b'YD2lDXO_Qxm8.wav' b'YDenqVdOM-Zs.wav' b'YD-2TW_McvsE.wav'
 b'YDb4B9qu3C6I.wav' b'YDWoYo4ZEReM.wav']
hdf5_path (1912134,)
[b'unbalanced_train_segments_part13.h5'
 b'unbalanced_train_segments_part13.h5'
 b'unbalanced_train_segments_part13.h5'
 b'unbalanced_train_segments_part13.h5'
 b'unbalanced_train_segments_part13.h5']
index_in_hdf5 (1912134,)
[0 1 2 3 4]
target (1912134,)
[array([408,   0], dtype=int32) array([360,   0], dtype=int32)
 array([515,   0], dtype=int32) array([0], dtype=int32)
 array([0], dtype=int32) array([0], dtype=int32)
 array([137, 270], dtype=int32) array([347], dtype=int32)
 array([185, 188], dtype=int32) array([0], dtype=int32)]
kfold (1912134,)
[6 0 1 2 5]
0 : 191232
1 : 191228
2 : 191224
3 : 191221
4 : 191217
5 : 191210
6 : 191205
7 : 191201
8 : 191199
9 : 191197


In [3]:
output_file = '/media/ubuntu/ssd2t/AIGroup/Audio-Data/audioset/unbalanced_train_mini/unbalanced_train_segments_part11.h5'
with h5py.File(output_file, "r") as h5_file:
    print("H5文件中的数据集名称:", list(h5_file.keys()))
    print('audio_name', h5_file['audio_name'].shape)
    print(h5_file["audio_name"][:5])
    print('logmel', h5_file['logmel'].shape)
    print(h5_file["logmel"][1])
    print('target', h5_file['target'].shape)
    print(h5_file["target"][:5])

H5文件中的数据集名称: ['audio_name', 'logmel', 'target']
audio_name (1234,)
[b'YAi9D2-Tf1xQ.wav' b'YAlCJe05xDtE.wav' b'YAjhqPnuqUBA.wav'
 b'YB0qeLU3z1Q8.wav' b'YAwYLvv6YSuo.wav']
logmel (1234, 1001, 64)
[[-24.692692 -33.159607 -25.293123 ... -63.749714 -80.83298  -88.37987 ]
 [-28.62009  -25.131784 -22.639704 ... -66.45151  -86.215355 -88.0531  ]
 [-21.723978 -24.42577  -25.887566 ... -65.07728  -89.40936  -88.50618 ]
 ...
 [-19.664597 -24.890335 -28.182716 ... -71.29067  -86.75225  -87.67377 ]
 [-25.007627 -32.237576 -27.871927 ... -67.84478  -76.171455 -78.35288 ]
 [-24.724806 -30.691755 -34.52453  ... -60.461487 -66.433105 -68.792015]]
target (1234,)
[array([0], dtype=int32) array([0], dtype=int32)
 array([137, 146], dtype=int32) array([137], dtype=int32)
 array([431], dtype=int32)]
